// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("BibleViewController")]
	public partial class BibleViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITableView __mt_LibrariesTableView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("LibrariesTableView")]
		private MonoTouch.UIKit.UITableView LibrariesTableView {
			get {
				this.__mt_LibrariesTableView = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("LibrariesTableView")));
				return this.__mt_LibrariesTableView;
			}
			set {
				this.__mt_LibrariesTableView = value;
				this.SetNativeField("LibrariesTableView", value);
			}
		}
	}
}
