// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DonationsViewController")]
	public partial class DonationsViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIImageView __mt_CoinsImageView;
		
		private MonoTouch.UIKit.UIImageView __mt_BoxImageView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CoinsImageView")]
		private MonoTouch.UIKit.UIImageView CoinsImageView {
			get {
				this.__mt_CoinsImageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("CoinsImageView")));
				return this.__mt_CoinsImageView;
			}
			set {
				this.__mt_CoinsImageView = value;
				this.SetNativeField("CoinsImageView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("BoxImageView")]
		private MonoTouch.UIKit.UIImageView BoxImageView {
			get {
				this.__mt_BoxImageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("BoxImageView")));
				return this.__mt_BoxImageView;
			}
			set {
				this.__mt_BoxImageView = value;
				this.SetNativeField("BoxImageView", value);
			}
		}
	}
}
