// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("FavoritesViewController")]
	public partial class FavoritesViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITableView __mt_FavoritesTableView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("FavoritesTableView")]
		private MonoTouch.UIKit.UITableView FavoritesTableView {
			get {
				this.__mt_FavoritesTableView = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("FavoritesTableView")));
				return this.__mt_FavoritesTableView;
			}
			set {
				this.__mt_FavoritesTableView = value;
				this.SetNativeField("FavoritesTableView", value);
			}
		}
	}
}
