// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MessageCellViewController")]
	public partial class MessageCellViewController {
		
		private MonoTouch.UIKit.UILabel __mt_SubjectLabel;
		
		private MonoTouch.UIKit.UILabel __mt_DateLabel;
		
		private MonoTouch.UIKit.UILabel __mt_ContentLabel;
		
		private MonoTouch.UIKit.UITableViewCell __mt_Cell;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("SubjectLabel")]
		private MonoTouch.UIKit.UILabel SubjectLabel {
			get {
				this.__mt_SubjectLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("SubjectLabel")));
				return this.__mt_SubjectLabel;
			}
			set {
				this.__mt_SubjectLabel = value;
				this.SetNativeField("SubjectLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("DateLabel")]
		private MonoTouch.UIKit.UILabel DateLabel {
			get {
				this.__mt_DateLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("DateLabel")));
				return this.__mt_DateLabel;
			}
			set {
				this.__mt_DateLabel = value;
				this.SetNativeField("DateLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("ContentLabel")]
		private MonoTouch.UIKit.UILabel ContentLabel {
			get {
				this.__mt_ContentLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("ContentLabel")));
				return this.__mt_ContentLabel;
			}
			set {
				this.__mt_ContentLabel = value;
				this.SetNativeField("ContentLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("Cell")]
		private MonoTouch.UIKit.UITableViewCell Cell {
			get {
				this.__mt_Cell = ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("Cell")));
				return this.__mt_Cell;
			}
			set {
				this.__mt_Cell = value;
				this.SetNativeField("Cell", value);
			}
		}
	}
}
