// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MessageViewController")]
	public partial class MessageViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITableView __mt_tblMessages;
		
		private MonoTouch.UIKit.UITextField __mt_txtMessage;
		
		private MonoTouch.UIKit.UIView __mt_viewComposing;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tblMessages")]
		private MonoTouch.UIKit.UITableView tblMessages {
			get {
				this.__mt_tblMessages = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("tblMessages")));
				return this.__mt_tblMessages;
			}
			set {
				this.__mt_tblMessages = value;
				this.SetNativeField("tblMessages", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("txtMessage")]
		private MonoTouch.UIKit.UITextField txtMessage {
			get {
				this.__mt_txtMessage = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("txtMessage")));
				return this.__mt_txtMessage;
			}
			set {
				this.__mt_txtMessage = value;
				this.SetNativeField("txtMessage", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("viewComposing")]
		private MonoTouch.UIKit.UIView viewComposing {
			get {
				this.__mt_viewComposing = ((MonoTouch.UIKit.UIView)(this.GetNativeField("viewComposing")));
				return this.__mt_viewComposing;
			}
			set {
				this.__mt_viewComposing = value;
				this.SetNativeField("viewComposing", value);
			}
		}
	}
}
