// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("NewMessageViewController")]
	public partial class NewMessageViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextView __mt_MessageTextView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("MessageTextView")]
		private MonoTouch.UIKit.UITextView MessageTextView {
			get {
				this.__mt_MessageTextView = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("MessageTextView")));
				return this.__mt_MessageTextView;
			}
			set {
				this.__mt_MessageTextView = value;
				this.SetNativeField("MessageTextView", value);
			}
		}
	}
}
