// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("PsalmViewController")]
	public partial class PsalmViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_NoLabel;
		
		private MonoTouch.UIKit.UILabel __mt_CaptionLabel;
		
		private MonoTouch.UIKit.UILabel __mt_AuthorLabel;
		
		private MonoTouch.UIKit.UITextView __mt_VersesTextView;
		
		private MonoTouch.UIKit.UIScrollView __mt_ContentScrollView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("NoLabel")]
		private MonoTouch.UIKit.UILabel NoLabel {
			get {
				this.__mt_NoLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("NoLabel")));
				return this.__mt_NoLabel;
			}
			set {
				this.__mt_NoLabel = value;
				this.SetNativeField("NoLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CaptionLabel")]
		private MonoTouch.UIKit.UILabel CaptionLabel {
			get {
				this.__mt_CaptionLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("CaptionLabel")));
				return this.__mt_CaptionLabel;
			}
			set {
				this.__mt_CaptionLabel = value;
				this.SetNativeField("CaptionLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("AuthorLabel")]
		private MonoTouch.UIKit.UILabel AuthorLabel {
			get {
				this.__mt_AuthorLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("AuthorLabel")));
				return this.__mt_AuthorLabel;
			}
			set {
				this.__mt_AuthorLabel = value;
				this.SetNativeField("AuthorLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("VersesTextView")]
		private MonoTouch.UIKit.UITextView VersesTextView {
			get {
				this.__mt_VersesTextView = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("VersesTextView")));
				return this.__mt_VersesTextView;
			}
			set {
				this.__mt_VersesTextView = value;
				this.SetNativeField("VersesTextView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("ContentScrollView")]
		private MonoTouch.UIKit.UIScrollView ContentScrollView {
			get {
				this.__mt_ContentScrollView = ((MonoTouch.UIKit.UIScrollView)(this.GetNativeField("ContentScrollView")));
				return this.__mt_ContentScrollView;
			}
			set {
				this.__mt_ContentScrollView = value;
				this.SetNativeField("ContentScrollView", value);
			}
		}
	}
}
