// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("PsalmsViewController")]
	public partial class PsalmsViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITableView __mt_CategoriesTableView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CategoriesTableView")]
		private MonoTouch.UIKit.UITableView CategoriesTableView {
			get {
				this.__mt_CategoriesTableView = ((MonoTouch.UIKit.UITableView)(this.GetNativeField("CategoriesTableView")));
				return this.__mt_CategoriesTableView;
			}
			set {
				this.__mt_CategoriesTableView = value;
				this.SetNativeField("CategoriesTableView", value);
			}
		}
	}
}
