// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dk.kirkeapp {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("RootViewController")]
	public partial class RootViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_btnMessages;
		
		private MonoTouch.UIKit.UIButton __mt_btnCalendar;
		
		private MonoTouch.UIKit.UIButton __mt_btnDonation;
		
		private MonoTouch.UIKit.UIButton __mt_btnBible;
		
		private MonoTouch.UIKit.UIButton __mt_btnPsalms;
		
		private MonoTouch.UIKit.UIButton __mt_btnFavorites;
		
		private MonoTouch.UIKit.UIButton __mt_btnAbout;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnMessages")]
		private MonoTouch.UIKit.UIButton btnMessages {
			get {
				this.__mt_btnMessages = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnMessages")));
				return this.__mt_btnMessages;
			}
			set {
				this.__mt_btnMessages = value;
				this.SetNativeField("btnMessages", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnCalendar")]
		private MonoTouch.UIKit.UIButton btnCalendar {
			get {
				this.__mt_btnCalendar = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnCalendar")));
				return this.__mt_btnCalendar;
			}
			set {
				this.__mt_btnCalendar = value;
				this.SetNativeField("btnCalendar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnDonation")]
		private MonoTouch.UIKit.UIButton btnDonation {
			get {
				this.__mt_btnDonation = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnDonation")));
				return this.__mt_btnDonation;
			}
			set {
				this.__mt_btnDonation = value;
				this.SetNativeField("btnDonation", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnBible")]
		private MonoTouch.UIKit.UIButton btnBible {
			get {
				this.__mt_btnBible = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnBible")));
				return this.__mt_btnBible;
			}
			set {
				this.__mt_btnBible = value;
				this.SetNativeField("btnBible", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnPsalms")]
		private MonoTouch.UIKit.UIButton btnPsalms {
			get {
				this.__mt_btnPsalms = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnPsalms")));
				return this.__mt_btnPsalms;
			}
			set {
				this.__mt_btnPsalms = value;
				this.SetNativeField("btnPsalms", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnFavorites")]
		private MonoTouch.UIKit.UIButton btnFavorites {
			get {
				this.__mt_btnFavorites = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnFavorites")));
				return this.__mt_btnFavorites;
			}
			set {
				this.__mt_btnFavorites = value;
				this.SetNativeField("btnFavorites", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btnAbout")]
		private MonoTouch.UIKit.UIButton btnAbout {
			get {
				this.__mt_btnAbout = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btnAbout")));
				return this.__mt_btnAbout;
			}
			set {
				this.__mt_btnAbout = value;
				this.SetNativeField("btnAbout", value);
			}
		}
	}
}
